version: '2'
services:
    cassandra:
        image: cassandra:latest
        ports:
            - 7199:7199
            - 9042:9042
            - 9160:9160
        volumes:
            - $PWD/database-data:/var/lib/cassandra
        container_name: cassandra