#  Author: Martin Josefik, Marek Rychly

version: '3'

services:
    cassandra:
        build: ./cassandra-custom
        image: martinfit/cassandra:3
        container_name: cassandra
        restart: unless-stopped
        networks:
            default:
                # fixed IP address to access externally
                ipv4_address: 172.16.254.31
        ports:
            - 7199:7199
            - 9042:9042
            - 9160:9160
        environment:
            CASSANDRA_BROADCAST_ADDRESS: 172.16.254.31
            #COMPOSE_CONVERT_WINDOWS_PATHS: 1
        volumes:
            - ./cassandra-data:/var/lib/cassandra
            - ./cassandra-data:/home/cassandra/.cassandra
            - ./cassandra-custom/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    mongodb:
        image: mongo:3.4
        container_name: mongodb
        restart: unless-stopped
        networks:
            default:
                # fixed IP address to access externally
                ipv4_address: 172.16.254.32
        ports:
            - 27017:27017
    hadoop:
        image: sequenceiq/hadoop-docker:2.7.1
        container_name: hadoop
        networks:
            default:
                # fixed IP address to access externally
                ipv4_address: 172.16.254.33
        ports:
            - 8020:8020
            - 8042:8042
            - 8088:8088
            - 9000:9000
            - 10020:10020
            - 19888:19888
            - 50010:50010
            - 50020:50020
            - 50070:50070
            - 50075:50075
            - 50090:50090
    kafka:
        image: wurstmeister/kafka:1.0.1
        container_name: kafka
        networks:
            default:
                # fixed IP address to access externally
                ipv4_address: 172.16.254.34
        ports:
            - 9092:9092
        environment:
            KAFKA_ADVERTISED_HOST_NAME: 172.16.254.34
            KAFKA_ZOOKEEPER_CONNECT: 172.16.254.35:2181
            KAFKA_ADVERTISED_PORT: 9092
            KAFKA_REPLICA_FETCH_MAX_BYTES: 500000000
            KAFKA_MESSAGE_MAX_BYTES: 500000000
            KAFKA_REQUEST_TIMEOUT_MS: 50000
            KAFKA_DELETE_TOPIC_ENABLE: "true"
            #KAFKA_HEAP_OPTS: -Xmx512M -Xms256M
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    zookeeper:
        image: wurstmeister/zookeeper
        container_name: zookeeper
        networks:
            default:
                # fixed IP address to access externally
                ipv4_address: 172.16.254.35
        ports:
            - 2181:2181

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "172.16.254.0/24"
