#  Author: Martin Josefik
#  Date: 2017-11-11 14:38:55 +0000 (Sat, 11 Nov 2017)

version: '3'

services:
    cassandra-official:
        image: cassandra:latest
    cassandra:
        build: cassandra-custom
    mongodb:
        image: mongo:latest
    hadoop:
        image: sequenceiq/hadoop-docker:latest
    zookeeper:
        image: wurstmeister/zookeeper:latest
    kafka:
        image: wurstmeister/kafka:latest
    maven:
        build: maven-jdk-9-slim-custom
