#  Author: Martin Josefik
#  Date: 2017-11-11 14:38:55 +0000 (Sat, 11 Nov 2017)

version: '3'

services:
    cassandra:
        image: martinfit/cassandra:latest
        container_name: cassandra
        restart: unless-stopped
        network_mode: "bridge"
        ports:
            - 7199:7199
            - 9042:9042
            - 9160:9160
        #environment:
        #    COMPOSE_CONVERT_WINDOWS_PATHS: 1
        volumes:
            - data:/var/lib/cassandra
            - data:/home/cassandra/.cassandra
            - ./cassandra-custom/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: unless-stopped
        network_mode: "bridge"
        ports:
            - 27017:27017
    hadoop:
        image: sequenceiq/hadoop-docker:latest
        container_name: hadoop
        network_mode: "bridge"
        #environment:
        #    CORE_CONF_fs_defaultFS: hdfs://192.168.99.100:9000
        ports:
            - 8020:8020
            - 8042:8042
            - 8088:8088
            - 9000:9000
            - 10020:10020
            - 19888:19888
            - 50010:50010
            - 50020:50020
            - 50070:50070
            - 50075:50075
            - 50090:50090
        # Windows hack
        #       route add 172.17.0.0/16 192.168.99.100
        #       route add 172.18.0.0/16 192.168.99.100
    kafka:
        image: wurstmeister/kafka
        container_name: kafka
        network_mode: "bridge"
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
            KAFKA_ZOOKEEPER_CONNECT: 192.168.99.100:2181
            KAFKA_ADVERTISED_PORT: 9092
            KAFKA_REPLICA_FETCH_MAX_BYTES: 500000000
            KAFKA_MESSAGE_MAX_BYTES: 500000000
            KAFKA_REQUEST_TIMEOUT_MS: 50000
            KAFKA_DELETE_TOPIC_ENABLE: "true"
            #KAFKA_HEAP_OPTS: -Xmx512M -Xms256M
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    zookeeper:
        image: wurstmeister/zookeeper
        container_name: zookeeper
        network_mode: "bridge"
        ports:
            - "2181:2181"

volumes:
    data: {}
