version: '2'
services:
    zookeeper:
        image: wurstmeister/zookeeper
        container_name: zookeeper
        ports:
            - "2181:2181"
    kafka:
        image: wurstmeister/kafka
        container_name: kafka
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_PORT: 9092
            KAFKA_REPLICA_FETCH_MAX_BYTES: 500000000
            KAFKA_MESSAGE_MAX_BYTES: 500000000
            KAFKA_REQUEST_TIMEOUT_MS: 50000
            KAFKA_DELETE_TOPIC_ENABLE: "true"
            #KAFKA_HEAP_OPTS: -Xmx512M -Xms256M
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
