version: '2'
services:
    hadoop:
        image: sequenceiq/hadoop-docker:latest
        environment:
            CORE_CONF_fs_defaultFS: hdfs://192.168.99.100:8020
        ports:
            - 8020:8020
            - 8042:8042
            - 8088:8088
            #- 9000:9000
            #- 10020:10020
            - 19888:19888
            - 50010:50010
            - 50020:50020
            - 50070:50070
            - 50075:50075
            - 50090:50090
        container_name: hadoop